name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - compiler: gdc
            ccommand: gdc
          - compiler: ldc
            ccommand: ldmd2
    env:
      DC: ${{ matrix.ccommand }}
      DEBUG: db,msg,user
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ${{ matrix.compiler }} libsqlite3-dev

      - name: Build
        run: make

  artifacts:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [x86_64]
    env:
      DC: ldmd2 -static -O
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add gcc ldc ldc-static make musl-dev sqlite-dev sqlite-static

      - name: Build
        run: make

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.arch }}-linux
          path: bin
